server:
  port: 9901
spring:
#数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/local_test?serverTimezone=UTC
    username: root
    password: 941206
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
#  JPA配置
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

#  redis配置
  redis:
    host: 120.79.224.47
    port: 6379
    timeout: 10000
    password: 123
    lettuce:
      pool:
        max-active: 30
        max-wait: 6000
        max-idle: 20
        min-idle: 5
